[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "python vinted_notifications.py"
healthcheckPath = "/"
healthcheckPort = 8000
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
